name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      ##image: 'devkitpro/devkita64'
      image: 'ghcr.io/ely3m/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: build
        run: make -j2
        
      - name: test
        run: |
          pwd
          ls -la 
          ls -la out
        
      - name: Zipping up Release folder
        run: 7z a release.zip "${{ github.workspace }}/out"
        
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          prerelease: false
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: release.zip
          name: "Switch Release #${{ github.run_number }}"